# Generated by Django 5.0.1 on 2024-03-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
