# Generated by Django 5.0.1 on 2024-03-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='ending_stop',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='starting_stop',
            field=models.DateTimeField(null=True),
        ),
    ]
