# Generated by Django 5.0.1 on 2024-05-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketorder',
            old_name='ending_stop',
            new_name='end_stop',
        ),
        migrations.RenameField(
            model_name='ticketorder',
            old_name='starting_stop',
            new_name='start_stop',
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
