# Generated by Django 5.0.1 on 2024-03-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_ticketorder_ending_time_ticketorder_starting_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketorder',
            old_name='ending_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='ticketorder',
            old_name='starting_time',
            new_name='start_time',
        ),
    ]
