# Generated by Django 5.0.1 on 2024-03-23 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_ticketorder_ending_stop_ticketorder_starting_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorder',
            name='ending_stop',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='starting_stop',
        ),
    ]
