# Generated by Django 5.0.1 on 2024-03-17 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_ticketorder_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorder',
            name='id',
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='ticket_order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
