# Generated by Django 5.0.1 on 2024-03-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_rename_ending_time_ticketorder_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorder',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='start_time',
        ),
    ]
