# Generated by Django 5.0.1 on 2024-03-17 11:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_ticketorder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='ticket_order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
