# Generated by Django 5.0.1 on 2024-03-17 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_ticketorder_quantity_and_more'),
        ('vendor', '0010_busdetail_is_active_route_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='Route_id',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, related_name='order_route', to='vendor.route'),
            preserve_default=False,
        ),
    ]
