# Generated by Django 5.0.1 on 2024-03-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_ticketorder_route_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketorder',
            old_name='Route_id',
            new_name='route_id',
        ),
    ]
