# Generated by Django 5.0.1 on 2024-03-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_remove_ticketorder_end_stop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorder',
            name='bus_detail',
        ),
    ]
