# Generated by Django 5.0.1 on 2024-03-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_remove_ticketorder_bus_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=0, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_order_id',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='signature_id',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
