# Generated by Django 5.0.1 on 2024-03-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_remove_payment_id_alter_payment_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ticket',
        ),
        migrations.AddField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(default=5, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
