# Generated by Django 5.0.1 on 2024-03-18 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_payment_id_alter_payment_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ticket',
        ),
    ]
