# Generated by Django 5.0.1 on 2024-03-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='OTP_expire',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
