# Generated by Django 5.0.1 on 2024-02-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_vendordetails_address_alter_vendordetails_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='OTP',
            field=models.IntegerField(null=True),
        ),
    ]
