# Generated by Django 5.0.1 on 2024-01-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_vendordetails_approve_alter_vendordetails_is_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='vendordetails',
            name='company_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
