# Generated by Django 5.0.1 on 2024-02-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='GSTIN',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
