# Generated by Django 5.0.1 on 2024-03-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_otp_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='OTP_expire',
        ),
    ]
