# Generated by Django 5.0.1 on 2024-02-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_vendordetails_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordetails',
            name='country',
            field=models.CharField(default='India', max_length=50, null=True),
        ),
    ]
