# Generated by Django 5.0.1 on 2024-01-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_is_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendordetails',
            name='is_vendor',
        ),
    ]
