# Generated by Django 5.0.1 on 2024-01-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthenticator', '0002_account_date_joined_alter_account_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
