# Generated by Django 5.0.1 on 2024-01-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthenticator', '0004_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
