# Generated by Django 5.0.1 on 2024-01-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAuthenticator', '0005_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
