# Generated by Django 5.0.1 on 2024-04-02 17:04

import bus.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(blank=True, max_length=256)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='busStopImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_img', models.FileField(null=True, upload_to='bus/stop/')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.busstop')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(blank=True, null=True)),
                ('time', models.IntegerField(null=True, validators=[bus.models.ConnectedRoute.validate_positive_duration])),
                ('bus_stop_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop1', to='bus.busstop')),
                ('bus_stop_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop2', to='bus.busstop')),
            ],
        ),
    ]
