# Generated by Django 5.0.1 on 2024-01-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bus_stop',
            new_name='BusStop',
        ),
    ]
