# Generated by Django 5.0.1 on 2024-02-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_rename_connected_route_connectedroute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstop',
            old_name='lon',
            new_name='lng',
        ),
    ]
