# Generated by Django 5.0.1 on 2024-03-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_busstop_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstop',
            name='user_id',
        ),
    ]
