# Generated by Django 5.0.1 on 2024-02-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_rename_lon_busstop_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectedroute',
            name='time',
        ),
        migrations.AddField(
            model_name='connectedroute',
            name='distance_time',
            field=models.IntegerField(null=True),
        ),
    ]
