# Generated by Django 5.0.1 on 2024-02-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_rename_lon_busstop_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedroute',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
