# Generated by Django 5.0.1 on 2024-02-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_remove_connectedroute_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectedroute',
            old_name='distance_time',
            new_name='time',
        ),
    ]
