# Generated by Django 5.0.1 on 2024-02-14 11:36

import bus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_rename_distance_time_connectedroute_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedroute',
            name='time',
            field=models.DurationField(null=True, validators=[bus.models.ConnectedRoute.validate_positive_duration]),
        ),
    ]
