# Generated by Django 5.0.1 on 2024-02-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_remove_connectedroute_time_connectedroute_time_hlk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectedroute',
            old_name='time_hlk',
            new_name='time',
        ),
    ]
